FROM quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-25 AS build
WORKDIR /workspace
USER root
RUN microdnf install findutils -y
COPY gradlew gradlew.bat settings.gradle.kts build.gradle.kts ./
COPY gradle gradle
COPY src src
RUN chown -R quarkus:quarkus /workspace
USER quarkus
RUN ./gradlew quarkusBuild -Dquarkus.native.enabled=true -Dquarkus.package.jar.enabled=false --no-daemon

FROM quay.io/quarkus/ubi9-quarkus-micro-image:2.0
WORKDIR /work
COPY --from=build --chown=1001:root /workspace/build/*-runner /work/application
RUN chmod 775 /work/application
EXPOSE 8080
ENV LANG=C.UTF-8
USER 1001
ENTRYPOINT ["/work/application", "-Dquarkus.http.host=0.0.0.0"]
